### ISSUE TITLE
Trouble printing cutter arm

### ISSUE THREAD

**Issue by D20180** [SouthAsh1/Xol-metrix#3]
V0.2 esun ABS+ Orcaslicer no Z-hop

Having problems printing, the built in support won't stay on the one strip supporting it, curls up and gets knocked off.

**Comment by SouthAsh1** [comment]
So not saying that I can't modify the model to make it slightly easier to print but how high are your fans? 
I also believe that Esun ABS+ is not the friendlest at printing and likes to warp on installed parts based on the voron discord.

However I will take a look this weekend as got a few minor updates to work on :)

**Comment by SouthAsh1** [comment]
Closing issue as I have modified the model to make it easier to print and D20180 has not commented any further.
