### ISSUE TITLE
Ball bearing is not standard BOM?

### ISSUE THREAD

**Issue by LandonPatmore** [SouthAsh1/Xol-metrix#4]
I have an ERCF and looked through my kit contents that came from https://dfh.fm/products/enraged-rabbit-carrot-feeder?_pos=6&_sid=a5b37ae28&_ss=r and also the official BOM here https://docs.google.com/spreadsheets/d/1A_qeNeaVprh_iPbvLcLjvJ2o2NfCzjuJam3K3RkWW0w/edit#gid=0 and there does not seem to be a mention of a ball bearing anywhere there?

**Comment by SouthAsh1** [comment]
It is a 5.5mm ball bearing that is standard on the ERCF v2 BOM for the ERCT buffer system I will update the repo to clarify sorry about that!

**Comment by LandonPatmore** [comment]
Ah looks like I have an ERCG v1 build, whoops!

**Comment by SouthAsh1** [comment]
All good!
