### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bobwarsrvng** [SouthAsh1/Xol-metrix#7]
Step #2:
Next drill out the 2 Flanged M2 Heatset Inserts with a 5/64 inch drill bit. Then use the #2 center drill bit to chamfer the top of one and the bottom of the other. ⚠⚠ Make sure you thuroghly clean the inserts of brass when done! ⚠⚠

I have a couple of questions: 

1. What if I can't get the [HM20X157C] listed in the BOM? Digikey and Mouser are both on backorder and everyone else seems to want multiple thousands to process an order. I only need a couple. 

1.a Would this work? Comes pre-chamfered

https://www.amazon.com/gp/product/B088QJG676/ref=ewc_pr_img_1?smid=A2L1PKBL5IWW8M&psc=1

3. I'm trying to understand the purpose of the chamfer here. If I am understanding, I would drill out the threads to make a nice smooth passage for filament and then countersinking the top / bottom to allow for the filament to have a small margin of error when inserting. Like a funnel. 

and a bonus, 

⚠⚠ Make sure you **<spelling>thuroghly</spelling>** clean the inserts of brass when done! ⚠⚠

Also, I feel I must explain myself for doing this as an issue. The discord link won't let a non-student like me to access the link (Its been more than a few years) and I couldn't find your username in Discord. I might just be old though. 

Otherwise, this is an amazing project! 

I hope it ends up being mainlined!

**Comment by SouthAsh1** [comment]
So I'm looking at an alternative for the heatset just haven't decided what I'm wanting to go with yet. That heatset is too small, there is barely anything there after drilling it out. Last yes the chamfer is for small margins of error when the filament is re-inserted. Though my design is a lot tighter than others, it's better to have than not.

Idk about the discord link thing as it should work as long as you are in the Armchair discord.
