### ISSUE TITLE
BambuLab Supports do not line up with hotend mount

### ISSUE THREAD

**Issue by StacyLow** [SouthAsh1/Xol-metrix#8]
The bambulab supports only line up with the hotend mount for the BambuLab Fan Heatset model (which looks to be the long version). I have fixed this and will raise a PR

**Comment by SouthAsh1** [comment]
Hahaha oops I _really_ messed those up! They are fixed now, I'll try to get the CAD updated at some point.

**Comment by StacyLow** [comment]
Oh that was quick! I've made a branch with the updated CAD, do you want me to publish it?

**Comment by SouthAsh1** [comment]
No it's ok I already have it I just have to re-upload it, and I think I might restructure the CAD files to how Taz has the official Repo
